name: Release

on:
  pull_request:
    branches: [ main ]
#  push:
#    tags:
#      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            asset_name: 'nyt-crossword-downloader-mac.zip'
          - os: windows-latest
            asset_name: 'nyt-crossword-downloader-win.zip'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: |
        pipenv install --deploy --dev     
    - name: Create macOS Install Package
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        pipenv run pyinstaller main.py -n nyt-crossword-downloader --add-data 'assets/README.txt:.' --target-arch universal2
    - name: Create Windows Install Package
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        pipenv run pyinstaller main.py -n nyt-crossword-downloader --add-data 'assets\README.txt:.'
    - name: Archive Package
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'dist'
        path: 'nyt-crossword-downloader'
        filename: 'nyt-crossword-downloader.zip'
    - name: Upload Binaries to GitHub Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'dist/nyt-crossword-downloader.zip'
        asset_name: ${{ matrix.asset_name }}
#        tag: ${{ github.ref }}
        tag: '1.0.0-alpha2'
        overwrite: true
